services:
  foundryup:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    working_dir: '/workspace'
    ports:
      - 8545:8545
      - 30303:30303
    volumes:
      - ../workspace:/workspace